# Site settings
author: Yehuda Makarov
title: Making It Work the Way Your Imagination Decided
header-img: img/home-bg.png
email: yehudamakarov@gmail.com
copyright_name: Yehuda Makarov
description: > # this means to ignore newlines until "baseurl:"
  Some musings that occurred over the course of my development journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yehudamakarov

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
