# Site settings
title: Making It Work the Way Your Imagination Decided
header-img: img/home-bg.png
email: yehudamakarov@gmail.com
copyright_name: yehudamakarov
description: > # this means to ignore newlines until "baseurl:"
  Some ideas that come about from having a UX geared fullStack approach.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yehudamakarov
learn_profile: yehudamakarov
email_username: yehudamakarov@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
